# Generated by Django 4.0.4 on 2022-05-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mymodel_field2'),
        ('app', '0002_mymodel_field3'),
    ]

    operations = [
    ]
